stages:
  - install
  - test
  - build

install-job:
  stage: install
  image: node
  script:
    - npm ci

test-job:
  stage: test
  image: node
  dependencies:
    - install-job
  script:
    - npm run test

build-job:
  stage: build
  image: node
  dependencies:
    - install-job
  script:
    - npm run build
